"""create models

Revision ID: 2bd7e873f2fb
Revises: 
Create Date: 2025-12-22 13:50:20.796990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '2bd7e873f2fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('type', sa.Enum('HOME', 'WORK', 'RESTAURANT', 'CUSTOM', name='address_type'), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_restaurant_id'), 'addresses', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_index('ix_addresses_user_type', 'addresses', ['user_id', 'type'], unique=False)
    op.create_table('coupons',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('per_customer_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_coupon_code')
    )
    op.create_table('membership_benefits',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_membership_benefits_name')
    )
    op.create_table('membership_tiers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('fee_rules', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_membership_tiers_name')
    )
    op.create_table('payouts',
    sa.Column('stripe_payout_id', sa.String(length=255), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'PAID', 'FAILED', 'CANCELED', name='payout_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payouts_status', 'payouts', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_permissions_name')
    )
    op.create_table('promotions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('code_normalized', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('PERCENT', 'FIXED', 'FREE_DELIVERY', 'BOGO', name='promotion_type'), nullable=False),
    sa.Column('scope', sa.Enum('ORDER', 'ITEM', 'RESTAURANT', 'GLOBAL', name='promotion_scope'), nullable=False),
    sa.Column('min_order_cents', sa.Integer(), nullable=True),
    sa.Column('rules', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('code_normalized = lower(code)', name='ck_promotions_code_normalized'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promotions_active', 'promotions', ['is_active'], unique=False)
    op.create_index('ix_promotions_code_normalized', 'promotions', ['code_normalized'], unique=True)
    op.create_index(op.f('ix_promotions_deleted_at'), 'promotions', ['deleted_at'], unique=False)
    op.create_table('restaurants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='restaurant_status'), nullable=False),
    sa.Column('cuisines', postgresql.ARRAY(String(length=64)), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('stripe_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stripe_account_id'], ['stripe_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_restaurants_created_at', 'restaurants', ['created_at'], unique=False)
    op.create_index(op.f('ix_restaurants_owner_id'), 'restaurants', ['owner_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_table('service_areas',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_areas_active', 'service_areas', ['is_active'], unique=False)
    op.create_table('stripe_accounts',
    sa.Column('stripe_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=True),
    sa.Column('onboarding_status', sa.String(length=64), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('courier_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_account_id', name='uq_stripe_account_id')
    )
    op.create_index(op.f('ix_stripe_accounts_courier_id'), 'stripe_accounts', ['courier_id'], unique=False)
    op.create_index(op.f('ix_stripe_accounts_restaurant_id'), 'stripe_accounts', ['restaurant_id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'COURIER', 'RESTAURANT_OWNER', 'STAFF', 'ADMIN', name='user_role_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lower'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(
        'ix_users_email_lower',
        'users',
        [sa.text('lower(email)')],
        unique=True,
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('carts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.Enum('PICKUP', 'DELIVERY', name='order_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carts_customer_active', 'carts', ['customer_id', 'restaurant_id'], unique=False)
    op.create_index(op.f('ix_carts_customer_id'), 'carts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_carts_restaurant_id'), 'carts', ['restaurant_id'], unique=False)
    op.create_table('courier_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_profiles_user_id'), 'courier_profiles', ['user_id'], unique=True)
    op.create_table('customer_memberships',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'EXPIRED', name='membership_status'), nullable=False),
    sa.Column('source', sa.Enum('PAID', 'EARNED', name='membership_source'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['membership_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_memberships_customer_id'), 'customer_memberships', ['customer_id'], unique=False)
    op.create_index('ix_customer_memberships_status', 'customer_memberships', ['status'], unique=False)
    op.create_index(op.f('ix_customer_memberships_tier_id'), 'customer_memberships', ['tier_id'], unique=False)
    op.create_table('menu_versions',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='menu_version_status'), nullable=False),
    sa.Column('published_by_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'version_number', name='uq_menu_version_number')
    )
    op.create_index(op.f('ix_menu_versions_published_by_id'), 'menu_versions', ['published_by_id'], unique=False)
    op.create_index(op.f('ix_menu_versions_restaurant_id'), 'menu_versions', ['restaurant_id'], unique=False)
    op.create_table('menus',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menus_restaurant_active', 'menus', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_menus_restaurant_id'), 'menus', ['restaurant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notification_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_table('order_type_configurations',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('supports_delivery', sa.Boolean(), nullable=False),
    sa.Column('supports_pickup', sa.Boolean(), nullable=False),
    sa.Column('prep_time_delivery_minutes', sa.Integer(), nullable=True),
    sa.Column('prep_time_pickup_minutes', sa.Integer(), nullable=True),
    sa.Column('pickup_hours', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('payment_methods',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_method_id', name='uq_payment_method_id')
    )
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('promotion_conditions',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_conditions_promotion_id'), 'promotion_conditions', ['promotion_id'], unique=False)
    op.create_table('restaurant_configurations',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('min_order_cents', sa.Integer(), nullable=False),
    sa.Column('fee_settings', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('tax_settings', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('throttles', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('restaurant_owner_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verification_status', sa.String(length=64), nullable=True),
    sa.Column('stripe_account_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['stripe_account_id'], ['stripe_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_owner_profiles_user_id'), 'restaurant_owner_profiles', ['user_id'], unique=True)
    op.create_table('restaurant_staff_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'MENU_EDITOR', 'VIEWER', name='restaurant_staff_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'restaurant_id', name='uq_restaurant_staff')
    )
    op.create_index(op.f('ix_restaurant_staff_users_restaurant_id'), 'restaurant_staff_users', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_staff_users_user_id'), 'restaurant_staff_users', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('route_plans',
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('courier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_plans_courier_id'), 'route_plans', ['courier_id'], unique=False)
    op.create_index(op.f('ix_route_plans_restaurant_id'), 'route_plans', ['restaurant_id'], unique=False)
    op.create_table('tier_benefits',
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('benefit_id', sa.UUID(), nullable=False),
    sa.Column('benefit_params', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['membership_benefits.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['membership_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_id', 'benefit_id', name='uq_tier_benefit')
    )
    op.create_index(op.f('ix_tier_benefits_benefit_id'), 'tier_benefits', ['benefit_id'], unique=False)
    op.create_index(op.f('ix_tier_benefits_tier_id'), 'tier_benefits', ['tier_id'], unique=False)
    op.create_table('transfer_records',
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=False),
    sa.Column('destination_account_id', sa.String(length=255), nullable=False),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELED', name='transfer_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_transfer_id', name='uq_transfer_id')
    )
    op.create_index(op.f('ix_transfer_records_payout_id'), 'transfer_records', ['payout_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'restaurant_id', name='uq_user_roles')
    )
    op.create_index(op.f('ix_user_roles_restaurant_id'), 'user_roles', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_payment_method_id', sa.UUID(), nullable=True),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('membership_tier_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['default_payment_method_id'], ['payment_methods.id'], ),
    sa.ForeignKeyConstraint(['membership_tier_id'], ['membership_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_profiles_user_id'), 'customer_profiles', ['user_id'], unique=True)
    op.create_table('membership_history',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('previous_tier_id', sa.UUID(), nullable=True),
    sa.Column('new_tier_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['customer_memberships.id'], ),
    sa.ForeignKeyConstraint(['new_tier_id'], ['membership_tiers.id'], ),
    sa.ForeignKeyConstraint(['previous_tier_id'], ['membership_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_membership_history_membership', 'membership_history', ['membership_id'], unique=False)
    op.create_index(op.f('ix_membership_history_membership_id'), 'membership_history', ['membership_id'], unique=False)
    op.create_index(op.f('ix_membership_history_new_tier_id'), 'membership_history', ['new_tier_id'], unique=False)
    op.create_index(op.f('ix_membership_history_previous_tier_id'), 'membership_history', ['previous_tier_id'], unique=False)
    op.create_table('membership_subscriptions',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=120), nullable=True),
    sa.Column('billing_cycle', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'EXPIRED', name='membership_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['customer_memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id', name='uq_membership_subscription_id')
    )
    op.create_index(op.f('ix_membership_subscriptions_membership_id'), 'membership_subscriptions', ['membership_id'], unique=True)
    op.create_table('menu_categories',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_deleted_at'), 'menu_categories', ['deleted_at'], unique=False)
    op.create_index('ix_menu_categories_menu_active', 'menu_categories', ['menu_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_menu_categories_menu_id'), 'menu_categories', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_categories_restaurant_id'), 'menu_categories', ['restaurant_id'], unique=False)
    op.create_table('menu_change_logs',
    sa.Column('menu_version_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('before_snapshot', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('after_snapshot', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['menu_version_id'], ['menu_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_change_logs_actor_id'), 'menu_change_logs', ['actor_id'], unique=False)
    op.create_index('ix_menu_change_logs_entity', 'menu_change_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_menu_change_logs_menu_version_id'), 'menu_change_logs', ['menu_version_id'], unique=False)
    op.create_table('orders',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.Enum('PICKUP', 'DELIVERY', name='order_type'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CONFIRMED', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['customer_memberships.id'], ),
    sa.ForeignKeyConstraint(['promo_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_membership_id'), 'orders', ['membership_id'], unique=False)
    op.create_index(op.f('ix_orders_promo_id'), 'orders', ['promo_id'], unique=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('delivery_tasks',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('pickup_address_id', sa.UUID(), nullable=True),
    sa.Column('dropoff_address_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'DELIVERED', 'CANCELLED', name='delivery_task_status'), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dropoff_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_tasks_order_id'), 'delivery_tasks', ['order_id'], unique=True)
    op.create_index(op.f('ix_delivery_tasks_restaurant_id'), 'delivery_tasks', ['restaurant_id'], unique=False)
    op.create_index('ix_delivery_tasks_status', 'delivery_tasks', ['status'], unique=False)
    op.create_table('menu_items',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('price_delivery_cents', sa.Integer(), nullable=True),
    sa.Column('price_pickup_cents', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(String(length=64)), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('out_of_stock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_category_id'), 'menu_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_menu_items_deleted_at'), 'menu_items', ['deleted_at'], unique=False)
    op.create_index('ix_menu_items_menu_active', 'menu_items', ['menu_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_menu_items_menu_id'), 'menu_items', ['menu_id'], unique=False)
    op.create_index('ix_menu_items_restaurant_active', 'menu_items', ['restaurant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_menu_items_restaurant_id'), 'menu_items', ['restaurant_id'], unique=False)
    op.create_table('order_adjustments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SERVICE_FEE', 'MEMBERSHIP_DISCOUNT', 'PROMO_DISCOUNT', 'REFUND', 'OTHER', name='adjustment_type'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_adjustments_order', 'order_adjustments', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_adjustments_order_id'), 'order_adjustments', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'CONFIRMED', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status'), nullable=False),
    sa.Column('to_status', sa.Enum('CREATED', 'CONFIRMED', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='order_status'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_actor_id'), 'order_status_history', ['actor_id'], unique=False)
    op.create_index('ix_order_status_history_order', 'order_status_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payment_intent_records',
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('REQUIRES_PAYMENT_METHOD', 'REQUIRES_CONFIRMATION', 'REQUIRES_ACTION', 'PROCESSING', 'SUCCEEDED', 'CANCELED', name='payment_intent_status'), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id', name='uq_payment_intent_id')
    )
    op.create_index(op.f('ix_payment_intent_records_order_id'), 'payment_intent_records', ['order_id'], unique=False)
    op.create_table('pickup_schedules',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('requested_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_code', sa.String(length=32), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_pickup_schedule_order')
    )
    op.create_index(op.f('ix_pickup_schedules_order_id'), 'pickup_schedules', ['order_id'], unique=True)
    op.create_table('promotion_redemptions',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'VOIDED', 'REVERSED', name='promotion_redemption_status'), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_promo_redemptions_customer', 'promotion_redemptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_promotion_redemptions_customer_id'), 'promotion_redemptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_promotion_redemptions_order_id'), 'promotion_redemptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_promotion_redemptions_promotion_id'), 'promotion_redemptions', ['promotion_id'], unique=False)
    op.create_table('ratings',
    sa.Column('target_type', sa.Enum('RESTAURANT', 'COURIER', name='rating_target'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(String(length=64)), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_order_id'), 'ratings', ['order_id'], unique=False)
    op.create_index(op.f('ix_ratings_rater_id'), 'ratings', ['rater_id'], unique=False)
    op.create_index('ix_ratings_target', 'ratings', ['target_type', 'target_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', 'CLOSED', name='support_ticket_status'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_customer_id'), 'support_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_order_id'), 'support_tickets', ['order_id'], unique=False)
    op.create_index('ix_support_tickets_status', 'support_tickets', ['status'], unique=False)
    op.create_table('availability_rules',
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('menu_category_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['menu_category_id'], ['menu_categories.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_rules_menu_category_id'), 'availability_rules', ['menu_category_id'], unique=False)
    op.create_index('ix_availability_rules_menu_item', 'availability_rules', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_availability_rules_menu_item_id'), 'availability_rules', ['menu_item_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_items_cart', 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_menu_item_id'), 'cart_items', ['menu_item_id'], unique=False)
    op.create_table('charge_records',
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='charge_status'), nullable=False),
    sa.Column('refunded_amount_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intent_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_charge_id', name='uq_charge_id')
    )
    op.create_index(op.f('ix_charge_records_payment_intent_id'), 'charge_records', ['payment_intent_id'], unique=False)
    op.create_table('courier_assignments',
    sa.Column('delivery_task_id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OFFERED', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='courier_assignment_status'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_task_id'], ['delivery_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_assignments_courier_id'), 'courier_assignments', ['courier_id'], unique=False)
    op.create_index(op.f('ix_courier_assignments_delivery_task_id'), 'courier_assignments', ['delivery_task_id'], unique=False)
    op.create_index('ix_courier_assignments_task', 'courier_assignments', ['delivery_task_id'], unique=False)
    op.create_table('courier_location_updates',
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('delivery_task_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_task_id'], ['delivery_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courier_location_updates_courier', 'courier_location_updates', ['courier_id'], unique=False)
    op.create_index(op.f('ix_courier_location_updates_courier_id'), 'courier_location_updates', ['courier_id'], unique=False)
    op.create_index(op.f('ix_courier_location_updates_delivery_task_id'), 'courier_location_updates', ['delivery_task_id'], unique=False)
    op.create_table('menu_item_option_groups',
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('min_choices', sa.Integer(), nullable=True),
    sa.Column('max_choices', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_option_groups_deleted_at'), 'menu_item_option_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_menu_item_option_groups_menu_item_id'), 'menu_item_option_groups', ['menu_item_id'], unique=False)
    op.create_index('ix_option_groups_menu_item_active', 'menu_item_option_groups', ['menu_item_id', 'is_active'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price_cents', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_menu_item_id'), 'order_items', ['menu_item_id'], unique=False)
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('refund_records',
    sa.Column('stripe_refund_id', sa.String(length=255), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='refund_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intent_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_refund_id', name='uq_refund_id')
    )
    op.create_index(op.f('ix_refund_records_payment_intent_id'), 'refund_records', ['payment_intent_id'], unique=False)
    op.create_table('menu_item_options',
    sa.Column('option_group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_delta_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['option_group_id'], ['menu_item_option_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_options_deleted_at'), 'menu_item_options', ['deleted_at'], unique=False)
    op.create_index('ix_menu_item_options_group_active', 'menu_item_options', ['option_group_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_menu_item_options_option_group_id'), 'menu_item_options', ['option_group_id'], unique=False)
    op.create_table('cart_item_options',
    sa.Column('cart_item_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('option_group_id', sa.UUID(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('price_delta_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], ),
    sa.ForeignKeyConstraint(['option_group_id'], ['menu_item_option_groups.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['menu_item_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_item_options_cart_item', 'cart_item_options', ['cart_item_id'], unique=False)
    op.create_index(op.f('ix_cart_item_options_cart_item_id'), 'cart_item_options', ['cart_item_id'], unique=False)
    op.create_index(op.f('ix_cart_item_options_option_group_id'), 'cart_item_options', ['option_group_id'], unique=False)
    op.create_index(op.f('ix_cart_item_options_option_id'), 'cart_item_options', ['option_id'], unique=False)
    op.create_table('order_item_options',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('option_group_id', sa.UUID(), nullable=True),
    sa.Column('name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('price_delta_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['option_group_id'], ['menu_item_option_groups.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['menu_item_options.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_options_option_group_id'), 'order_item_options', ['option_group_id'], unique=False)
    op.create_index(op.f('ix_order_item_options_option_id'), 'order_item_options', ['option_id'], unique=False)
    op.create_index('ix_order_item_options_order_item', 'order_item_options', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_order_item_options_order_item_id'), 'order_item_options', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_options_order_item_id'), table_name='order_item_options')
    op.drop_index('ix_order_item_options_order_item', table_name='order_item_options')
    op.drop_index(op.f('ix_order_item_options_option_id'), table_name='order_item_options')
    op.drop_index(op.f('ix_order_item_options_option_group_id'), table_name='order_item_options')
    op.drop_table('order_item_options')
    op.drop_index(op.f('ix_cart_item_options_option_id'), table_name='cart_item_options')
    op.drop_index(op.f('ix_cart_item_options_option_group_id'), table_name='cart_item_options')
    op.drop_index(op.f('ix_cart_item_options_cart_item_id'), table_name='cart_item_options')
    op.drop_index('ix_cart_item_options_cart_item', table_name='cart_item_options')
    op.drop_table('cart_item_options')
    op.drop_index(op.f('ix_menu_item_options_option_group_id'), table_name='menu_item_options')
    op.drop_index('ix_menu_item_options_group_active', table_name='menu_item_options')
    op.drop_index(op.f('ix_menu_item_options_deleted_at'), table_name='menu_item_options')
    op.drop_table('menu_item_options')
    op.drop_index(op.f('ix_refund_records_payment_intent_id'), table_name='refund_records')
    op.drop_table('refund_records')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_option_groups_menu_item_active', table_name='menu_item_option_groups')
    op.drop_index(op.f('ix_menu_item_option_groups_menu_item_id'), table_name='menu_item_option_groups')
    op.drop_index(op.f('ix_menu_item_option_groups_deleted_at'), table_name='menu_item_option_groups')
    op.drop_table('menu_item_option_groups')
    op.drop_index(op.f('ix_courier_location_updates_delivery_task_id'), table_name='courier_location_updates')
    op.drop_index(op.f('ix_courier_location_updates_courier_id'), table_name='courier_location_updates')
    op.drop_index('ix_courier_location_updates_courier', table_name='courier_location_updates')
    op.drop_table('courier_location_updates')
    op.drop_index('ix_courier_assignments_task', table_name='courier_assignments')
    op.drop_index(op.f('ix_courier_assignments_delivery_task_id'), table_name='courier_assignments')
    op.drop_index(op.f('ix_courier_assignments_courier_id'), table_name='courier_assignments')
    op.drop_table('courier_assignments')
    op.drop_index(op.f('ix_charge_records_payment_intent_id'), table_name='charge_records')
    op.drop_table('charge_records')
    op.drop_index(op.f('ix_cart_items_menu_item_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_index('ix_cart_items_cart', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_availability_rules_menu_item_id'), table_name='availability_rules')
    op.drop_index('ix_availability_rules_menu_item', table_name='availability_rules')
    op.drop_index(op.f('ix_availability_rules_menu_category_id'), table_name='availability_rules')
    op.drop_table('availability_rules')
    op.drop_index('ix_support_tickets_status', table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_order_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_customer_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index('ix_ratings_target', table_name='ratings')
    op.drop_index(op.f('ix_ratings_rater_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_order_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_promotion_redemptions_promotion_id'), table_name='promotion_redemptions')
    op.drop_index(op.f('ix_promotion_redemptions_order_id'), table_name='promotion_redemptions')
    op.drop_index(op.f('ix_promotion_redemptions_customer_id'), table_name='promotion_redemptions')
    op.drop_index('ix_promo_redemptions_customer', table_name='promotion_redemptions')
    op.drop_table('promotion_redemptions')
    op.drop_index(op.f('ix_pickup_schedules_order_id'), table_name='pickup_schedules')
    op.drop_table('pickup_schedules')
    op.drop_index(op.f('ix_payment_intent_records_order_id'), table_name='payment_intent_records')
    op.drop_table('payment_intent_records')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index('ix_order_status_history_order', table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_actor_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_adjustments_order_id'), table_name='order_adjustments')
    op.drop_index('ix_order_adjustments_order', table_name='order_adjustments')
    op.drop_table('order_adjustments')
    op.drop_index(op.f('ix_menu_items_restaurant_id'), table_name='menu_items')
    op.drop_index('ix_menu_items_restaurant_active', table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_menu_id'), table_name='menu_items')
    op.drop_index('ix_menu_items_menu_active', table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_deleted_at'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('ix_delivery_tasks_status', table_name='delivery_tasks')
    op.drop_index(op.f('ix_delivery_tasks_restaurant_id'), table_name='delivery_tasks')
    op.drop_index(op.f('ix_delivery_tasks_order_id'), table_name='delivery_tasks')
    op.drop_table('delivery_tasks')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_promo_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_membership_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_menu_change_logs_menu_version_id'), table_name='menu_change_logs')
    op.drop_index('ix_menu_change_logs_entity', table_name='menu_change_logs')
    op.drop_index(op.f('ix_menu_change_logs_actor_id'), table_name='menu_change_logs')
    op.drop_table('menu_change_logs')
    op.drop_index(op.f('ix_menu_categories_restaurant_id'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_menu_id'), table_name='menu_categories')
    op.drop_index('ix_menu_categories_menu_active', table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_deleted_at'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_membership_subscriptions_membership_id'), table_name='membership_subscriptions')
    op.drop_table('membership_subscriptions')
    op.drop_index(op.f('ix_membership_history_previous_tier_id'), table_name='membership_history')
    op.drop_index(op.f('ix_membership_history_new_tier_id'), table_name='membership_history')
    op.drop_index(op.f('ix_membership_history_membership_id'), table_name='membership_history')
    op.drop_index('ix_membership_history_membership', table_name='membership_history')
    op.drop_table('membership_history')
    op.drop_index(op.f('ix_customer_profiles_user_id'), table_name='customer_profiles')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_restaurant_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_transfer_records_payout_id'), table_name='transfer_records')
    op.drop_table('transfer_records')
    op.drop_index(op.f('ix_tier_benefits_tier_id'), table_name='tier_benefits')
    op.drop_index(op.f('ix_tier_benefits_benefit_id'), table_name='tier_benefits')
    op.drop_table('tier_benefits')
    op.drop_index(op.f('ix_route_plans_restaurant_id'), table_name='route_plans')
    op.drop_index(op.f('ix_route_plans_courier_id'), table_name='route_plans')
    op.drop_table('route_plans')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_restaurant_staff_users_user_id'), table_name='restaurant_staff_users')
    op.drop_index(op.f('ix_restaurant_staff_users_restaurant_id'), table_name='restaurant_staff_users')
    op.drop_table('restaurant_staff_users')
    op.drop_index(op.f('ix_restaurant_owner_profiles_user_id'), table_name='restaurant_owner_profiles')
    op.drop_table('restaurant_owner_profiles')
    op.drop_table('restaurant_configurations')
    op.drop_index(op.f('ix_promotion_conditions_promotion_id'), table_name='promotion_conditions')
    op.drop_table('promotion_conditions')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_table('order_type_configurations')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_menus_restaurant_id'), table_name='menus')
    op.drop_index('ix_menus_restaurant_active', table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_menu_versions_restaurant_id'), table_name='menu_versions')
    op.drop_index(op.f('ix_menu_versions_published_by_id'), table_name='menu_versions')
    op.drop_table('menu_versions')
    op.drop_index(op.f('ix_customer_memberships_tier_id'), table_name='customer_memberships')
    op.drop_index('ix_customer_memberships_status', table_name='customer_memberships')
    op.drop_index(op.f('ix_customer_memberships_customer_id'), table_name='customer_memberships')
    op.drop_table('customer_memberships')
    op.drop_index(op.f('ix_courier_profiles_user_id'), table_name='courier_profiles')
    op.drop_table('courier_profiles')
    op.drop_index(op.f('ix_carts_restaurant_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_customer_id'), table_name='carts')
    op.drop_index('ix_carts_customer_active', table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stripe_accounts_restaurant_id'), table_name='stripe_accounts')
    op.drop_index(op.f('ix_stripe_accounts_courier_id'), table_name='stripe_accounts')
    op.drop_table('stripe_accounts')
    op.drop_index('ix_service_areas_active', table_name='service_areas')
    op.drop_table('service_areas')
    op.drop_table('roles')
    op.drop_index(op.f('ix_restaurants_owner_id'), table_name='restaurants')
    op.drop_index('ix_restaurants_created_at', table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_promotions_deleted_at'), table_name='promotions')
    op.drop_index('ix_promotions_code_normalized', table_name='promotions')
    op.drop_index('ix_promotions_active', table_name='promotions')
    op.drop_table('promotions')
    op.drop_table('permissions')
    op.drop_index('ix_payouts_status', table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('membership_tiers')
    op.drop_table('membership_benefits')
    op.drop_table('coupons')
    op.drop_index('ix_addresses_user_type', table_name='addresses')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_restaurant_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
