"""add payment restaurant attribution and allocations

Revision ID: 60cb4a17a107
Revises: 2bd7e873f2fb
Create Date: 2025-12-22 14:29:34.972140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60cb4a17a107'
down_revision = '2bd7e873f2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    transfer_type_enum = postgresql.ENUM(
        'RESTAURANT_PAYOUT',
        'COURIER_PAYOUT',
        'PLATFORM_FEE_SHARE',
        'REFUND_REVERSAL',
        name='transfer_type',
    )
    transfer_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('restaurant_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'restaurant_id', name='uq_restaurant_likes')
    )
    op.create_index(op.f('ix_restaurant_likes_restaurant_id'), 'restaurant_likes', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_likes_user_id'), 'restaurant_likes', ['user_id'], unique=False)
    op.create_table('membership_receipts',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='membership_receipt_status'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['customer_memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_receipts_customer_id'), 'membership_receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_membership_receipts_membership_id'), 'membership_receipts', ['membership_id'], unique=False)
    op.create_table('order_restaurant_allocations',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('payout_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'restaurant_id', name='uq_order_restaurant_allocations')
    )
    op.create_index(op.f('ix_order_restaurant_allocations_order_id'), 'order_restaurant_allocations', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_restaurant_allocations_restaurant_id'), 'order_restaurant_allocations', ['restaurant_id'], unique=False)
    op.create_table('order_receipts',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=True),
    sa.Column('charge_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='receipt_status'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('provider_receipt_id', sa.String(length=255), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charge_records.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intent_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_order_receipts_order')
    )
    op.create_index(op.f('ix_order_receipts_charge_id'), 'order_receipts', ['charge_id'], unique=False)
    op.create_index(op.f('ix_order_receipts_customer_id'), 'order_receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_receipts_order_id'), 'order_receipts', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_receipts_payment_intent_id'), 'order_receipts', ['payment_intent_id'], unique=False)
    op.add_column('charge_records', sa.Column('restaurant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_charge_records_restaurant_id'), 'charge_records', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'charge_records', 'restaurants', ['restaurant_id'], ['id'])
    op.create_index('ix_orders_restaurant_created_at', 'orders', ['restaurant_id', 'created_at'], unique=False)
    op.add_column('payment_intent_records', sa.Column('restaurant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_payment_intent_records_restaurant_id'), 'payment_intent_records', ['restaurant_id'], unique=False)
    op.create_index('ix_payment_intents_restaurant_created_at', 'payment_intent_records', ['restaurant_id', 'created_at'], unique=False)
    op.create_foreign_key(None, 'payment_intent_records', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('payouts', sa.Column('restaurant_id', sa.UUID(), nullable=True))
    op.add_column('payouts', sa.Column('courier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payouts_courier_id'), 'payouts', ['courier_id'], unique=False)
    op.create_index(op.f('ix_payouts_restaurant_id'), 'payouts', ['restaurant_id'], unique=False)
    op.create_check_constraint(
        'ck_payouts_one_owner',
        'payouts',
        '(restaurant_id IS NOT NULL AND courier_id IS NULL) OR '
        '(restaurant_id IS NULL AND courier_id IS NOT NULL)',
    )
    op.create_foreign_key(None, 'payouts', 'users', ['courier_id'], ['id'])
    op.create_foreign_key(None, 'payouts', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('transfer_records', sa.Column('order_id', sa.UUID(), nullable=False))
    op.add_column('transfer_records', sa.Column('restaurant_id', sa.UUID(), nullable=False))
    op.add_column('transfer_records', sa.Column('destination_stripe_account_id', sa.UUID(), nullable=False))
    op.add_column('transfer_records', sa.Column('currency', sa.String(length=3), nullable=False))
    op.alter_column('transfer_records', 'transfer_type',
               existing_type=sa.VARCHAR(length=64),
               type_=transfer_type_enum,
               nullable=False,
               postgresql_using='upper(transfer_type)::transfer_type')
    op.create_index(op.f('ix_transfer_records_destination_stripe_account_id'), 'transfer_records', ['destination_stripe_account_id'], unique=False)
    op.create_index(op.f('ix_transfer_records_order_id'), 'transfer_records', ['order_id'], unique=False)
    op.create_index(op.f('ix_transfer_records_restaurant_id'), 'transfer_records', ['restaurant_id'], unique=False)
    op.create_unique_constraint('uq_transfer_order_type_destination', 'transfer_records', ['order_id', 'transfer_type', 'destination_stripe_account_id'])
    op.create_foreign_key(None, 'transfer_records', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'transfer_records', 'stripe_accounts', ['destination_stripe_account_id'], ['id'])
    op.create_foreign_key(None, 'transfer_records', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('transfer_records', 'destination_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    transfer_type_enum = postgresql.ENUM(
        'RESTAURANT_PAYOUT',
        'COURIER_PAYOUT',
        'PLATFORM_FEE_SHARE',
        'REFUND_REVERSAL',
        name='transfer_type',
    )

    op.add_column('transfer_records', sa.Column('destination_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transfer_records', type_='foreignkey')
    op.drop_constraint(None, 'transfer_records', type_='foreignkey')
    op.drop_constraint(None, 'transfer_records', type_='foreignkey')
    op.drop_constraint('uq_transfer_order_type_destination', 'transfer_records', type_='unique')
    op.drop_index(op.f('ix_transfer_records_restaurant_id'), table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_order_id'), table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_destination_stripe_account_id'), table_name='transfer_records')
    op.alter_column('transfer_records', 'transfer_type',
               existing_type=transfer_type_enum,
               type_=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('transfer_records', 'currency')
    op.drop_column('transfer_records', 'destination_stripe_account_id')
    op.drop_column('transfer_records', 'restaurant_id')
    op.drop_column('transfer_records', 'order_id')
    transfer_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'payouts', type_='foreignkey')
    op.drop_constraint(None, 'payouts', type_='foreignkey')
    op.drop_constraint('ck_payouts_one_owner', 'payouts', type_='check')
    op.drop_index(op.f('ix_payouts_restaurant_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_courier_id'), table_name='payouts')
    op.drop_column('payouts', 'courier_id')
    op.drop_column('payouts', 'restaurant_id')
    op.drop_constraint(None, 'payment_intent_records', type_='foreignkey')
    op.drop_index('ix_payment_intents_restaurant_created_at', table_name='payment_intent_records')
    op.drop_index(op.f('ix_payment_intent_records_restaurant_id'), table_name='payment_intent_records')
    op.drop_column('payment_intent_records', 'restaurant_id')
    op.drop_index('ix_orders_restaurant_created_at', table_name='orders')
    op.drop_constraint(None, 'charge_records', type_='foreignkey')
    op.drop_index(op.f('ix_charge_records_restaurant_id'), table_name='charge_records')
    op.drop_column('charge_records', 'restaurant_id')
    op.drop_index(op.f('ix_order_receipts_payment_intent_id'), table_name='order_receipts')
    op.drop_index(op.f('ix_order_receipts_order_id'), table_name='order_receipts')
    op.drop_index(op.f('ix_order_receipts_customer_id'), table_name='order_receipts')
    op.drop_index(op.f('ix_order_receipts_charge_id'), table_name='order_receipts')
    op.drop_table('order_receipts')
    op.drop_index(op.f('ix_order_restaurant_allocations_restaurant_id'), table_name='order_restaurant_allocations')
    op.drop_index(op.f('ix_order_restaurant_allocations_order_id'), table_name='order_restaurant_allocations')
    op.drop_table('order_restaurant_allocations')
    op.drop_index(op.f('ix_membership_receipts_membership_id'), table_name='membership_receipts')
    op.drop_index(op.f('ix_membership_receipts_customer_id'), table_name='membership_receipts')
    op.drop_table('membership_receipts')
    op.drop_index(op.f('ix_restaurant_likes_user_id'), table_name='restaurant_likes')
    op.drop_index(op.f('ix_restaurant_likes_restaurant_id'), table_name='restaurant_likes')
    op.drop_table('restaurant_likes')
    # ### end Alembic commands ###
