"""add stock tracking to menu items

Revision ID: d3684eed2e98
Revises: 8b2f3c9a1d2e
Create Date: 2025-12-24 15:45:29.066611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3684eed2e98'
down_revision = '8b2f3c9a1d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('menu_items', sa.Column('track_stock', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'track_stock')
    op.drop_column('menu_items', 'stock_quantity')
    # ### end Alembic commands ###
